### PR TITLE
1.1

### PR DESCRIPTION
**Pull request by ericgaspar**
## Problem

- *Description of why you made this PR*

## Solution

- *And how do you fix that problem*

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by lapineige** [comment]
I'm confused, is this to test the upgrade to v1.1 appart from rewrite to V2, compared to #65 ? 🤔

**Comment by ericgaspar** [comment]
#65 is still downloading Yakforms version 1.0.3 if I am not mistaken

**Comment by lapineige** [comment]
Oh yeah I don't understand how I made the mistake… I should have done it.

Anyway, thanks a lot ! :)

**Comment by ericgaspar** [comment]
!testme

**Comment by Salamandar** [comment]
Moving to #72  to prevent autoupdater from creating more PRs.

**Pull request closed without merging**
