### PR TITLE
Yakforms

### PR DESCRIPTION
**Pull request by zamentur**
## Problem

Yakforms 1.1 migration

## Solution

Note: it doesnt migrate the name of the app package...

## PR Status

- [ ] Code finished and ready to be reviewed/tested
- [ ] The fix/enhancement were manually tested (if applicable)

## Automatic tests

Automatic tests can be triggered on https://ci-apps-dev.yunohost.org/ *after creating the PR*, by commenting "!testme", "!gogogadgetoci" or "By the power of systemd, I invoke The Great App CI to test this Pull Request!". (N.B. : for this to work you need to be a member of the Yunohost-Apps organization)

### CODE REVIEW

**Comment by zamentur** [comment]
!testme

**Comment by zamentur** [comment]
!testmetitus

**Comment by Gredin67** [comment]
!testme

**Comment by lapineige** [comment]
> Note: it doesn't migrate the name of the app package...

I would not consider this a big deal for now as it is (more ?) referenced a bit everywhere as formerly framaforms, including on its own website.

Let's merge ?

**Pull request merged**
