### PR TITLE
fix spelling

### PR DESCRIPTION
**Pull request by yalh76**
to use same name as other apps https://dash.yunohost.org/app_maintainer_dash/jean-baptisteholcroft

### CODE REVIEW

**Comment by yalh76** [comment]
if someone from @YunoHost-Apps/apps-group can merge the small changes ^^

**Comment by Jibec** [comment]
Same here, what's the hurry?

**Comment by yalh76** [comment]
Very Sorry, no hurry, just cleanuping my PR... and trying to move them forward... I haven’t checked who was the maintainer....

**Comment by Jibec** [comment]
I'm unsure I wish to keep this app under my name. Let's keep it under my nickname.

**Comment by yalh76** [comment]
Is it OK if I make PR's for you other apps to change the maintainer to `jibec` or I let you manage that ?

https://dash.yunohost.org/app_maintainer_dash/jean-baptisteholcroft

**Comment by Jibec** [comment]
No sorry, please keep it as is

**Pull request closed without merging**
